name: CI - Python Unit Tests

on:
  push:
    branches: [ main]
  pull_request:
    branches: [ main]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      PROJECT_DIR: Lab4/lab4_tests_example 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.6"

      - name: Configure PYTHONPATH to project dir
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE/${PROJECT_DIR}" >> $GITHUB_ENV

      - name: Run unit tests
        run: |
          python -m unittest discover -v -s "${PROJECT_DIR}/tests" -p "test_*.py"
